@startuml
autonumber
BookReaderView --> BookReaderView : dispatchTouchEvent
BookReaderView --> BaseReaderView : dispatchTouchEvent

BookReaderView --> BookReaderView : onTouchEvent
BookReaderView --> BaseReaderView : onTouchEvent
BaseReaderView --> AbsHorGestureAnimController : dispatchTouchEvent



@enduml