@startuml

alt 普通wifi
== 查询设备 ==
    group group-ui
    CommonModel --> ITuyaHome : 通过TyGroupCoreKit.queryDeviceListToAddGroup方法
    end

    group homelib
    ITuyaHome --> HomeKitModel : 调用HomeKitModel.getGroupDeviceList
    HomeKitModel --> ITuyaGroupModel
    end

    group device
    ITuyaGroupModel --> GroupBusiness
    GroupBusiness --> 云端 : 调用s.m.dev.group.add.dev.list.2.0
    end
== 创建群组 ==
== 编辑群组 ==

else 普通zigbee或者433
== 查询设备 ==
    group group-ui
        CommonModel --> ITuyaHome : 通过TyGroupCoreKit.queryZigbeeDeviceListToAddGroup
        ITuyaHome --> CommonModel : 1.将GroupDeviceBean转成GroupDeviceDetailBean
    end

    group homelib
        ITuyaHome --> HomeKitModel : 调用HomeKitModel.getZigbeeGroupDeviceList
        HomeKitModel --> ITuyaHome : 直接返回
        HomeKitModel --> ITuyaGroupModel : 调用ITuyaGroupModel.getZigbeeGroupDeviceList
        ITuyaGroupModel --> HomeKitModel : 直接返回
    end

    group device
        ITuyaGroupModel --> GroupBusiness : GroupBusiness.queryZigbeeDevicesByProductId
        GroupBusiness --> 云端 : 调用s.m.dev.group.add.dev.list.3.0
        云端 --> ITuyaGroupModel : 1.将云端数据GroupDeviceRespBean转成GroupDeviceBean\n2.手动将设备设置为在线
    end
== 创建群组 ==
== 编辑群组 ==

else 标准zigbee
== 查询设备 ==
    group group-ui
    CommonModel --> GroupStandardWifiDeviceListModel : 通过标准wifi model来查询设备
    GroupStandardWifiDeviceListModel --> StandardBusiness:调用云端查询数据 \ntuya.m.device.group.standard.dev.list_1.1
    GroupStandardWifiDeviceListModel --> CommonModel : 将GroupDeviceDetailBean转成GroupDeviceBean
    end

== 创建群组 ==
== 编辑群组 ==

end
@enduml