@startuml
interface StateCallback
interface TextureManager
interface Callback


abstract class VideoTouchView
abstract class VideoView
abstract class VideoViewImpl

abstract class MusicView
abstract class MusicViewImpl

abstract class MediaView
abstract class MediaViewImpl


class VideoPlayer
class MusicPlayer

MediaView ..|> StateCallback
MediaView ..|> TextureManager
MediaView ..|> Callback

@enduml