@startuml
interface Operation
class OperationImpl
class Worker
class WorkRequest
class Build
class WorkManager{
  + WorkContinuation beginUniqueWork(uniqueWorkName,existingWorkPolicy,work)
}
class WorkContinuation{
  + WorkContinuation then(work)
  + {abstract} Operation enqueue()
}
class WorkInfo
class Constraints
Build --+ WorkRequest
Build ..> Constraints
WorkContinuation ..|> WorkManager
OperationImpl ..|> Operation
Operation ..> WorkContinuation
WorkRequest ..> WorkContinuation
Worker --o Build
@enduml