@startuml

class TyydVideoPlayerView {
  - void registerViews(View view)
}

class TyydMusicPlayerView {
  - void registerViews(View view)
  + void setOnMenuClickListener(OnMenuClickListener onMenuClickListener)
}

abstract BaseTyydViewPlayer{
  -- field --
  - HashMap<View, Integer> views
  - ITouchListener iTouchListener;
  - GestureDetectorCompat gestureDetectorCompat;
  - Consumer mCompletionConsumer;
  - Consumer mErrorConsumer;
  -- abstract --
  {abstract} # ITyydMediaPlayer getMediaPlayer(IRenderView renderView);
  {abstract} # @LayoutRes int getLayoutId();
  {abstract} # IRenderView getRenderView();
  {abstract} # @PlayerType int getPlayerType();
  -- 用户接口 --
  + void changeChapter(int index)
  + void startPlay()
  + void setState(@Status int mState)
  + void setDataAndSoruce(MediaInfoBean mediaInfoBean)
  + void setPlayeMode(@PlayerMode int mode)
  + void setProgressListener(IProgressListener progressListener)
  + void setChapterChangerListener(OnChapterChangerListener onChapterChangerListener)
  + void setOrientation()
  + void setOnCaptionListener(OnCaptionListener onCaptionListener)
  -- protected --
  # void register(View view, @BindingView int actions)
  # void bindingViews()
  # @PlayerMode int getPlayeMode()
  -- 横竖屏 --
  - void setPortrait(Activity activity)
  - void setLandscape(Activity activity)
  -- 初始化 --
  - void initConsumer()
  - void initViews(View key, Integer value)
  - void setClickListener(View key, final Integer value)
  - void initTouch()
  -- 播放逻辑 --
  - void checkNetwork()
  - void progressRenderView()
  - private void play()
  -- 字幕 --
  - void setCaptionUrl(final String url, final int type)
  - CaptionItem getCaption(int currentPosition)
  - File getDiskCacheDir(Context context, String uniqueName)
}

interface ITyydMediaPlayer{
  void setProgressListener(@NonNull IProgressListener progressListener);
  void setChapterChangerListener(OnChapterChangerListener onChapterChangerListener);
  void prepare(@NonNull PreparedListener preparedListener);
  void setCompletionConsumerBaseView(@NonNull Consumer consumerBaseView);
  void setErrorConsumerBaseView(@NonNull Consumer consumerBaseView);
  void play();
  void setDisplay(@NonNull SurfaceHolder surfaceHolder);
  void seekTo(int progress);
  void onPause();
  void onResume();
  void onStop();
  void onDestory();
  @PlayerState int getPlayerState();
  boolean isPlaying();
  int getCurPosition();
  List<BookContentBean> getCurMediaInfo();
  int getTotalTime();
  void changeSharpnessByIndex(int index) throws IOException;
  void setDataSource(List<Integer> urls,long bookId) throws IOException;
  void setDataSource(List<Integer> urls,long bookId,int index) throws IOException;
  void setPlayerMode(@PlayerMode int mode);
  @PlayerMode int getPlayerMode();
  void playNext();
  void playPre();
  void changeChapter(int index);
  void resetUrl() throws IOException;
  String getCurAudioRate();
  void retory();
}

class MediaPlayerProxy{
  -- field --
  - AudioManager mAudioManager;
  - Consumer mCompletionConsumer;
}
note left:播放器代理对象

ITyydMediaPlayer <|.. MediaPlayerProxy

class PlayerStatusManager{
  - IStatusChangeListener iStatusChangeListener;
  + void setStatus(@Status int action)
}
note right:播放器UI管理器

TyydVideoPlayerView  --|> BaseTyydViewPlayer
TyydMusicPlayerView  --|> BaseTyydViewPlayer
BaseTyydViewPlayer *-- MediaPlayerProxy
BaseTyydViewPlayer *-- PlayerStatusManager


MediaPlayerProxy *-- ITyydMediaPlayer

interface IRenderView{
  void saveCurrentFrame();
  SurfaceHolder getHolderView();
}

class SystemMediaPlayer{
  - MediaPlayer mediaPlayer;
  - IProgressListener progressListener;
  - MediaPlayerListener mMediaPlayerListener;
  - IRenderView mIRenderView;
}
SystemMediaPlayer *-- IRenderView
IRenderView <|.. TyydSurfaceView

ITyydMediaPlayer <|.. SystemMediaPlayer

class IJKMediaPlayer{

}

class TyydTextureView{

}

IJKMediaPlayer *-- IRenderView
ITyydMediaPlayer <|.. IJKMediaPlayer

IRenderView <|.. TyydTextureView

@enduml