@startuml
abstract GSYTextureRenderView
note right : 绘制View
abstract GSYVideoView{
  --  重要的属性 --
  + VideoAllCallBack
  + AudioManager
  + NetInfoModule
  # ViewGroup mTextureViewContainer
  -- 需要继承的方法 --
  {abstract} + GSYVideoViewBridge getGSYVideoManager()
  {abstract} # void setStateAndUi(int state);
  {abstract} + int getLayoutId()
  {abstract} + void startPlayLogic()
  {abstract} # boolean backFromFull(Context context)
  {abstract} # void releaseVideos()
}
abstract GSYVideoBaseManager{

}
note right : 视频回调与状态处理等相关层;自定义必须实现
abstract GSYVideoControlView{
  --  属性 --
  # GSYVideoProgressListener mGSYVideoProgressListener
}
note right : 播放UI的显示、控制层、手势处理等
abstract GSYBaseVideoPlayer
note right : 处理全屏和小屏幕逻辑
abstract GSYVideoPlayer{
  # boolean backFromFull(Context context)
  # void releaseVideos()
  # int getFullId()
  # int getSmallId()
}
note right : 兼容的空View，目前用于 GSYVideoManager的设置
class StandardGSYVideoPlayer
note right : 标准播放器，继承之后实现一些ui显示效果，如显示／隐藏ui，播放按键等

interface IPlayerManager{
  void setSpeed(float speed, boolean soundTouch)
  void seekTo(long time)
}
note right : 播放器内核管理类


interface GSYVideoViewBridge{

}
note right : Manager 与 View之间的接口




interface GSYMediaPlayerListener{
    void onPrepared();
    void onAutoCompletion();
    void onCompletion();
    void onBufferingUpdate(int percent);
    void onSeekComplete();
    void onError(int what, int extra);
    void onInfo(int what, int extra);
    void onVideoSizeChanged();
    void onBackFullscreen();
    void onVideoPause();
    void onVideoResume();
    void onVideoResume(boolean seek);
}
GSYMediaPlayerListener <|-- GSYVideoView


class GSYRenderView
interface IGSYRenderView

class GSYSurfaceView
class GSYTextureView
class GSYVideoGLView
class ProxyCacheManager
note right : 代理对象

GSYTextureRenderView <|-- GSYVideoView
GSYRenderView --* GSYTextureRenderView
IGSYRenderView --* GSYRenderView


GSYSurfaceView ..|> IGSYRenderView
GSYTextureView ..|> IGSYRenderView
GSYVideoGLView ..|> IGSYRenderView

class GSYVideoManager{

}

note right:视频管理单例
GSYVideoManager -- GSYVideoPlayer
GSYVideoBaseManager <|-- GSYVideoManager
IPlayerManager --* GSYVideoBaseManager
ICacheManager --* GSYVideoBaseManager
GSYVideoViewBridge <|.. GSYVideoBaseManager

ProxyCacheManager ..|> ICacheManager
HttpProxyCacheServer --* ProxyCacheManager


SystemPlayerManager ..|> IPlayerManager
IjkPlayerManager ..|> IPlayerManager
GSYExoPlayerManager ..|> IPlayerManager
Exo2PlayerManager ..|> IPlayerManager
AndroidMediaPlayer --* SystemPlayerManager
IjkMediaPlayer --* IjkPlayerManager
GSYExo2MediaPlayer --* GSYExoPlayerManager
IjkExo2MediaPlayer --* Exo2PlayerManager


GSYVideoView <|-- GSYVideoControlView
GSYVideoControlView <|-- GSYBaseVideoPlayer
GSYBaseVideoPlayer <|-- GSYVideoPlayer
GSYVideoPlayer <|-- StandardGSYVideoPlayer
GSYMediaPlayerListener --* GSYVideoBaseManager

@enduml