@startuml
class MotionLayout
class ConstraintLayout
abstract ConstraintHelper
abstract VirtualLayout
ConstraintHelper <|-- Group
ConstraintHelper <|-- Layer
ConstraintHelper <|-- MotionHelper
ConstraintHelper <|-- VirtualLayout
ConstraintHelper <|-- Barrier
ConstraintLayout <|-- MotionLayout




@enduml