@startuml
'https://plantuml.com/class-diagram
autonumber
participant CommonModel order 10
participant TuyaZigbeeGroup order 20
participant TuyaZigbeeGroupMonitorManager order 21
participant IDevModel order 30

CommonModel -> TuyaZigbeeGroup : addDeviceToGroup
TuyaZigbeeGroup -> TuyaZigbeeGroupMonitorManager : sendCommand
TuyaZigbeeGroupMonitorManager -> IDevModel : addZigBeeGroup

@enduml