@startuml
'https://plantuml.com/sequence-diagram

autonumber

participant SigMeshGroupListPresenter order 10
participant SigMeshModel order 20
participant SigMeshGroupDeviceListModel order 30
participant BluemeshBusiness order 40
participant TuyaSigMeshDevice order 50
participant TuyaCloudBlueMeshDevice order 60
participant TuyaSigmeshGroup order 31
participant 云端 order 10000

== 创建localId ==
SigMeshGroupListPresenter -> SigMeshModel : 传入meshId
SigMeshModel -> SigMeshGroupDeviceListModel : 调用getEnableGroupId，type为1，并处理返回的meshId
SigMeshGroupDeviceListModel -> BluemeshBusiness : 1：传入meshId和type，发起网络请求\n2：type用于区分sigmesh和私有mesh
BluemeshBusiness -> 云端 : 调用云端接口"tuya.m.device.ble.mesh.local.id.alloc"
BluemeshBusiness <-- 云端 : return localId
SigMeshGroupDeviceListModel <-- BluemeshBusiness : 转换localId
SigMeshModel <-- SigMeshGroupDeviceListModel : return localId

== 创建groupId ==
SigMeshModel -> TuyaSigMeshDevice : 创建groupId
TuyaSigMeshDevice -> TuyaCloudBlueMeshDevice : 1：删除已经存在的目标group（历史缓存）\n2:创建新的群组
TuyaCloudBlueMeshDevice -> 云端 : 1：请求云端接口"tuya.m.device.group.add"，创建groupId\n2:将群组添加到当前mesh下
TuyaCloudBlueMeshDevice <-- 云端 : groupId
TuyaSigMeshDevice <-- TuyaCloudBlueMeshDevice : groupId
SigMeshModel <-- TuyaSigMeshDevice : groupId


== 添加设备 ==
SigMeshModel -> SigMeshGroupDeviceListModel : operateDevice
SigMeshGroupDeviceListModel -> TuyaSigmeshGroup : addDevice

@enduml