@startuml

interface PageCarver{
  void drawPage(Canvas canvas, int index)
  Integer requestPrePage();
  Integer requestNextPage();
  void requestInvalidate();
  int getCurrentPageIndex();
  int getContentWidth();
  int getContentHeight();
  int getScreenWidth();
  int getScreenHeight();
  int getPageBackgroundColor();
  void onStartAnim(boolean isCancel);
  void onStopAnim(boolean isCancel);
}

class PageSnapshot
class PageSnapshotCache
class BookReaderView{
  - void initBookView()
}
class BookSettingParams
abstract class BaseReaderView{
  -- Override --
  # void onDraw(Canvss canvas)
  + boolean onTouchEvent(MotionEvent event)
  -- abstract --
  {abstract} void drawPageContent(Canvas canvas, int pageIndex)
  {abstract} void onPageEndChanged(int currentPage)
  {abstract} void onPageStartChange(int requestPage)
  {abstract} void onPageRequest(int currentPage, int requestPage)
}

BookReaderView --|> BaseReaderView

BookSettingParams --* BookReaderView
BookPageElement --* BookReaderView
BookTextSelectorElement --* BookReaderView
PageAnimController --* BookReaderView
PageSnapshotCache --* BookReaderView

PageSnapshotCache o-- PageSnapshot
PageCarver <|.. BaseReaderView

@enduml