@startuml
abstract class PageAnimController{
  -- abstract --
  {abstract} void dispatchTouchEvent(MotionEvent event, PageCarver pageCarver)
  {abstract} boolean dispatchDrawPage(Canvas canvas, PageCarver pageCarver)
  {abstract} void startAnim(int fromIndex, int toIndex, boolean isNext, PageCarver pageCarver)//翻页动画开始
  {abstract} void stopAnim(PageCarver pageCarver)
}

abstract class AbsHorGestureAnimController{
  - Scroller mScroller
  -- abstract --
  + abstract void onAnimStart(boolean isCancelAnim);
  + abstract void onAnimEnd(boolean isCancelAnim);
  + abstract void onRequestPage(boolean isRequestNext, int fromIndex, int toIndex, float x, float y);
  + abstract void onDrawAnim(Canvas canvas, boolean isCancelAnim, boolean isNext, PageCarver pageCarver);
  + abstract boolean isAnimStop();
}
class AutoAnimController
class NoAnimController
class PageTurningAnimController
class HorTranslationAnimController

interface PageCarver{
  void drawPage(Canvas canvas, int index)//区分第一页和其他页
  Integer requestPrePage();
  Integer requestNextPage();
  void requestInvalidate();
  int getCurrentPageIndex();
  int getContentWidth();
  int getContentHeight();
  int getScreenWidth();
  int getScreenHeight();
  int getPageBackgroundColor();
  void onStartAnim(boolean isCancel);
  void onStopAnim(boolean isCancel);
}
PageCarver --+ PageAnimController
PageAnimController <|-- AbsHorGestureAnimController
PageAnimController <|-- NoAnimController
PageAnimController <|-- AutoAnimController
AbsHorGestureAnimController <|-- PageTurningAnimController
AbsHorGestureAnimController <|-- HorTranslationAnimController

@enduml